### ISSUE TITLE
Error when call startManualCropper

### ISSUE THREAD

**Issue by EbelloImbox** [hannesa2/CVScanner#159]
Hello I am experimenting this issue when I use startManualCropper.

I am calling startManualCropper like that in Java: 

CVScanner.INSTANCE.startManualCropper(activity, uri, INTENT_RESULT_EDIT_PICTURE);

And this is the error in logcat:

Edit: If I use startScanner it launches fine.

```
2021-11-12 12:59:55.255 12828-12828/com.spotbros.defense E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.spotbros.defense, PID: 12828
    java.lang.RuntimeException: Unable to resume activity {com.spotbros.defense/info.hannes.cvscanner.crop.CropImageActivity}: android.view.InflateException: Binary XML file line #7 in com.spotbros.defense:layout/imagecropper_content: Binary XML file line #7 in com.spotbros.defense:layout/imagecropper_content: Error inflating class info.hannes.cvscanner.crop.CropImageView
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4761)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4794)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.view.InflateException: Binary XML file line #7 in com.spotbros.defense:layout/imagecropper_content: Binary XML file line #7 in com.spotbros.defense:layout/imagecropper_content: Error inflating class info.hannes.cvscanner.crop.CropImageView
     Caused by: android.view.InflateException: Binary XML file line #7 in com.spotbros.defense:layout/imagecropper_content: Error inflating class info.hannes.cvscanner.crop.CropImageView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at info.hannes.cvscanner.crop.ImageCropperFragment.onCreateView(ImageCropperFragment.java:87)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:458)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
        at android.app.Activity.performResume(Activity.java:8216)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4751)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4794)
2021-11-12 12:59:55.261 12828-12828/com.spotbros.defense E/AndroidRuntime:     at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter bitmap
        at info.hannes.cvscanner.crop.RotateBitmap.<init>(Unknown Source:2)
        at info.hannes.cvscanner.crop.ImageViewTouchBase.<init>(ImageViewTouchBase.java:37)
        at info.hannes.cvscanner.crop.CropImageView.<init>(CropImageView.java:34)
        	... 37 more
```

**Comment by hannesa2** [comment]
Indeed that a bug 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/3314607/141475772-4f6a7f77-81ce-4645-99f1-bc0d17766e4f.png">

**Comment by EbelloImbox** [comment]
I am glad to listen it, I was mad with this issue. 

Will you solve it soon in a 1.7.1 version? I can try to help you if you are busy, although I will need time to understand your library.

**Comment by hannesa2** [comment]
It's untested https://github.com/hannesa2/CVScanner/pull/160 please try it with 
`implementation 'com.github.hannesa2:CVScanner:FixNPE-SNAPSHOT'`

**Comment by EbelloImbox** [comment]
Sorry if I am a little bit late, I had some problems with new dependencies.

After test it, I have this exception: 

No content provider: /storage/emulated/0/Documents/ImboxDefense/ImboxDefense images/1636732466077

in this code line in Util class: 

`is` = context.contentResolver.openInputStream(imageUri) (line 77)

I am trying to see if this is my own problem, although I have tried to supply and uri from my own library and the result is the same.

**Comment by EbelloImbox** [comment]
To solve the last problem I used:

`Uri uri = Uri.fromFile(new File(path));`

If you provide a uri like this way, it works fine.
