### ISSUE TITLE
No view found id/container

### ISSUE THREAD

**Issue by EbelloImbox** [hannesa2/CVScanner#169]
A new bug with this last version using startManualCropper?

```
java.lang.RuntimeException: Unable to resume activity {com.spotbros.defense/info.hannes.cvscanner.crop.CropImageActivity}: java.lang.IllegalArgumentException: No view found for id 0x7f0a0195 (com.spotbros.defense:id/container) for fragment ImageCropperFragment{d622298} (c734b6cd-7a60-411c-81af-b5a861e7c2d9 id=0x7f0a0195)
        at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:55) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4206)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4238)
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:515) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:480) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:466) 
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418) 
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:387) 
        at java.lang.reflect.Method.invoke(Native Method)
        at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:52) 
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100) 
     Caused by: java.lang.IllegalArgumentException: No view found for id 0x7f0a0195 (com.spotbros.defense:id/container) for fragment ImageCropperFragment{d622298} (c734b6cd-7a60-411c-81af-b5a861e7c2d9 id=0x7f0a0195)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:387) 
        at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:52) 
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100) 
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62) 
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:458)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309) 
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279) 
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235) 
        at android.app.Activity.performResume(Activity.java:7964)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4196)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4238) 
        at java.lang.Thread.run(Thread.java:919) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
```

**Comment by hannesa2** [comment]
Does it works in the sample ? I see it comes from your app `com.spotbros.defense`

**Comment by EbelloImbox** [comment]
The problem was here in this part:

```
public override fun onCreate(icicle: Bundle?) {
        super.onCreate(icicle)
        window.addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN or WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        window.decorView.systemUiVisibility = (View.SYSTEM_UI_FLAG_FULLSCREEN
                or View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                or View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                or View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                or View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
                or View.SYSTEM_UI_FLAG_HIDE_NAVIGATION)
        supportActionBar?.hide()
        setContentView(R.layout.scanner_activity)
    }
```

I called scanner_activity to my layout too, unlucky day... xD
